//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.05.05 at 08:25:40 下午 CST 
//


package com.hotent.platform.xml.system;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

import com.hotent.core.model.BaseModel;
import com.hotent.platform.model.system.SysTemplate;



/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class SysTemplateObjectFactory {

    private final static QName _SysTemplate_QNAME = new QName("", "sysTemplate");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public SysTemplateObjectFactory() {
    }

    /**
     * Create an instance of {@link SysTemplates }
     * 
     */
    public SysTemplates createSysTemplates() {
        return new SysTemplates();
    }

    /**
     * Create an instance of {@link BaseModel }
     * 
     */
    public BaseModel createBaseModel() {
        return new BaseModel();
    }

    /**
     * Create an instance of {@link SysTemplate }
     * 
     */
    public SysTemplate createSysTemplate() {
        return new SysTemplate();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SysTemplate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "sysTemplate")
    public JAXBElement<SysTemplate> createSysTemplate(SysTemplate value) {
        return new JAXBElement<SysTemplate>(_SysTemplate_QNAME, SysTemplate.class, null, value);
    }

}
